# Generated by Django 3.2 on 2023-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='backend_media/', verbose_name='Фото пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Ученик'), ('teacher', 'Преподаватель')], max_length=50, null=True, verbose_name='Тип пользователя'),
        ),
    ]
